# Generated by Django 4.1.3 on 2022-11-06 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourcosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100, verbose_name='название категории')),
            ],
        ),
        migrations.CreateModel(
            name='InfotmationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='cумма')),
                ('time_operation', models.TimeField(auto_now_add=True, verbose_name='время')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('organization', models.CharField(max_length=100, verbose_name='организация')),
                ('description', models.TextField(max_length=250, verbose_name='описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(to='yourcosts.category'),
        ),
    ]
