# Generated by Django 4.1.3 on 2022-11-07 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourcosts', '0002_category_infotmationtransaction_user_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name_cat',), 'verbose_name': 'Категории расходов', 'verbose_name_plural': 'Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='infotmationtransaction',
            options={'ordering': ('user',), 'verbose_name': 'Информация по транзакции', 'verbose_name_plural': 'Информация по транзакции'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='infotmationtransaction',
            name='costs_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cумма'),
        ),
        migrations.AlterField(
            model_name='infotmationtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
